version: '3.1'
services:
  dev_postgresql:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hr_center
    volumes:
      - dev_db_volume:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
volumes:
  dev_db_volume:
