global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: article_bot
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ['article_bot:8000']

  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: postgres
    honor_labels: true
    static_configs:
      - targets: ['postgres_exporter:9187']